### ISSUE TITLE
If we post to the inbox of a deleted user, send a 404 or 410 error

### ISSUE THREAD

**Issue by srosset81** [activitypods/activitypods#348]
Currently it sends back a 500 error, and Mastodon servers keep on trying to send the activity:

```
[23:52:58.425Z] INFO  API: => POST /dame0/inbox
[23:52:58.470Z] INFO  API:    Call custom function in '  POST /:username([^/.][^/]+)/inbox => <Function>' alias
[23:52:58.470Z] INFO  API:    Call 'activitypub.api.inbox' action
[23:52:58.494Z] ERROR API:    Request error! Error : The dataset dame0 doesn't exist 
 Error: The dataset dame0 doesn't exist
    at Service.handler (/app/backend/node_modules/@semapps/triplestore/actions/query.js:31:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Service.getOwner (/app/backend/node_modules/@semapps/activitypub/services/activitypub/subservices/collection.js:408:23)
    at async Service.post (/app/backend/node_modules/@semapps/activitypub/services/activitypub/subservices/inbox.js:53:24)
    at async Service.inbox (/app/backend/node_modules/@semapps/activitypub/services/activitypub/subservices/api.js:52:7)
    at async Service.callAction (/app/backend/node_modules/moleculer-web/src/index.js:645:16)
    at async /app/backend/node_modules/moleculer-web/src/index.js:470:22 
Data: undefined
[23:52:58.498Z] INFO  API: <= 500 POST /dame0/inbox [+72.836 ms]
```

No error should be thrown. A 404 or 410 (Gone) error should be sent back.

**Comment by KrinsKumar** [comment]
Hey @srosset81, this looks like an interesting issue, can I work on this? if yes please assign this to me!!.

**Comment by srosset81** [comment]
@KrinsKumar That would be great!
A few indications:
- The changes will need to be made on the ActivityPub package of [SemApps](https://github.com/assemblee-virtuelle/semapps), and particularly the ActivityPubApiService. You can find instruction about linking ActivityPods to SemApps repo [here](https://github.com/activitypods/activitypods/tree/master/pod-provider#linking-to-semapps-packages).
- When a user deletes his Pod, [his account is marked with a "Tombstone"](https://github.com/activitypods/activitypods/blob/d49259edbbb66fb37fb4b1f11442855e75935404/pod-provider/backend/services/management.js#L77-L78) (this is persisted in another dataset, called usually "settings") During one year, no one will be able to register again that username. So it would be a good idea to return a 410 (Gone) error when we detect there is such a Tombstone, and simply a 404 error in other cases.

If you have any question, feel free to post them here or to write me on Matrix (my ID is `@sro81:matrix.org`)

**Comment by Laurin-W** [comment]
Hello @KrinsKumar from my side as well!
If you like, feel free to join our matrix space and write in the core dev channel, so I (or others) can respond as well :)
https://matrix.to/#/#activitypods:matrix.org

**Comment by srosset81** [comment]
Done here: https://github.com/assemblee-virtuelle/semapps/pull/1337
