### ISSUE TITLE
The backend is unable to restart after Fuseki went down

### ISSUE THREAD

**Issue by srosset81** [activitypods/activitypods#370]
We continously get this error message:

```
[09:52:09.461Z] WARN  ONTOLOGIES.REGISTRY: Reconnecting...
[09:52:09.462Z] INFO  TRIPLESTORE.DATASET: Dataset settings doesn't exist. Creating it...
[09:52:09.463Z] INFO  TRIPLESTORE.DATASET: Dataset settings doesn't exist. Creating it...
[09:52:09.465Z] INFO  TRIPLESTORE.DATASET: 
[09:52:09.465Z] ERROR AUTH.ACCOUNT: Connection error! Error: Error when creating unsecure dataset settings
    at Service.create (/app/backend/node_modules/@semapps/triplestore/subservices/dataset.js:62:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TripleStoreAdapter.connect (/app/backend/node_modules/@semapps/triplestore/adapter.js:22:5)
[09:52:09.466Z] ERROR ONTOLOGIES.REGISTRY: Connection error! Error: Error when creating unsecure dataset settings
    at Service.create (/app/backend/node_modules/@semapps/triplestore/subservices/dataset.js:62:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TripleStoreAdapter.connect (/app/backend/node_modules/@semapps/triplestore/adapter.js:22:5)
[09:52:09.465Z] INFO  TRIPLESTORE.DATASET: 
[09:52:10.465Z] WARN  AUTH.ACCOUNT: Reconnecting...
[09:52:10.466Z] INFO  BROKER: Waiting for service(s) 'triplestore'...
[09:52:10.466Z] INFO  BROKER: Service(s) 'triplestore' are available.
[09:52:10.471Z] INFO  BROKER: Waiting for service(s) 'triplestore'...
[09:52:10.471Z] INFO  BROKER: Service(s) 'triplestore' are available.
```

**Comment by srosset81** [comment]
It happened after the compact-datasets.sh script was called, because we then called `docker compose up -d` without including the `.env.local` file with the correct Fuseki password. Fixed in https://github.com/activitypods/deployment/commit/b3885ffc36dadaee77e6958f0e98c3d4521f9134

I wonder if there could be a way to prevent calling `docker compose up -d` directly... :thinking:

**Comment by srosset81** [comment]
> I wonder if there could be a way to prevent calling `docker compose up -d` directly... 🤔

I tried this https://github.com/activitypods/deployment/commit/e378890987f4a8c463884b4f252c0064ee4299ca#diff-e9cbb0224c4a3d23a6019ba557e0cd568c1ad5e1582ff1e335fb7d99b7a1055dR7 but unfortunately it didn't work so I had to revert.

According to this Docker issue https://github.com/docker/compose/issues/11122 the env files cannot be defined in the .env file, it only works if we pass it in the command line. So we are back to the same problem. Never mind.

**Comment by srosset81** [comment]
OK we will now only use the `.env` file and not `.env.local`. https://github.com/activitypods/deployment/commit/280c217f32f60253ca208687f307512b0ce0315c This way, we won't have this problem when restarting containers, and people will be able to use `docker compose` commands directly if they want.

I updated the docs for that: https://github.com/activitypods/activitypods/commit/a8c2d59870160c1a5dde14e541da1462bd392ba2
